<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom"><title></title><link href="Ganesh%20Kadam/" rel="alternate"></link><link href="Ganesh%20Kadam/feeds/technotes.atom.xml" rel="self"></link><id>Ganesh Kadam/</id><updated>2016-04-26T00:00:00+05:30</updated><entry><title>Gerrit Issue</title><link href="Ganesh%20Kadam/gerrit-issue.html" rel="alternate"></link><updated>2016-04-26T00:00:00+05:30</updated><author><name>Ganesh Kadam</name></author><id>tag:,2016-04-26:Ganesh Kadam/gerrit-issue.html</id><summary type="html">&lt;p&gt;I was working on shell a script. Now that it was complete I need to send that script for review.So I started to work on this.
Unfortunately I got the following error which took me almost took a day to resolve on my side. I decided not to ask my mentors until and unless  I am not able to rsolve this issue. This has been common issue amongst all of us interns!&lt;/p&gt;
&lt;pre class="literal-block"&gt;
[gkadam&amp;#64;dhcp201-114 cert-openstack-scripts]$ git review -R
Could not connect to gerrit.
Enter your gerrit username: gkadam&amp;#64;redhat.com
Trying again with ssh://gkadam&amp;#64;redhat.com&amp;#64;code.engineering.redhat.com:22/cert-openstack-scripts
&amp;lt;traceback object at 0x7fa7a448cb00&amp;gt;
We don't know where your gerrit is. Please manually create a remote
named &amp;quot;gerrit&amp;quot; and try again.
Could not connect to gerrit at ssh://gkadam&amp;#64;redhat.com&amp;#64;code.engineering.redhat.com:22/cert-openstack-acripts
Traceback (most recent call last):
File &amp;quot;/usr/bin/git-review&amp;quot;, line 11, in &amp;lt;module&amp;gt;
sys.exit(main())
File &amp;quot;/usr/lib/python2.7/site-packages/git_review/cmd.py&amp;quot;, line 1534, in main
sys.exit(e.EXIT_CODE)
AttributeError: 'GitReviewException' object has no attribute 'EXIT_CODE'
&lt;/pre&gt;
&lt;p&gt;After going through lots of google serarches I realized that, the things that were going wrong are already mentioned in the error code that I was getting. Before this I made a very silly mistake of deleting the existing file in that directory from which I have to send the file for review. So just after knowing this issue, I copied the new script in to the same directory again. Then I renamed to it's earlier name and performed following steps :&lt;/p&gt;
&lt;ol class="arabic simple"&gt;
&lt;li&gt;Cloned the repository to new location :&lt;/li&gt;
&lt;/ol&gt;
&lt;pre class="literal-block"&gt;
[gkadam&amp;#64;dhcp201-114 ~]$ git clone ssh://gkadam&amp;#64;code.engineering.redhat.com:22/cert-openstack-scripts
Cloning into 'cert-openstack-scripts'...
Checking connectivity... done.
warning: remote HEAD refers to nonexistent ref, unable to checkout.
&lt;/pre&gt;
&lt;ol class="arabic simple" start="2"&gt;
&lt;li&gt;Added the remote repository as we can see in the above error!&lt;/li&gt;
&lt;/ol&gt;
&lt;pre class="literal-block"&gt;
[gkadam&amp;#64;dhcp201-114 cert-openstack-scripts]$ git remote add gerrit ssh://gkadam&amp;#64;code.engineering.redhat.com:22/cert-openstack-scripts
&lt;/pre&gt;
&lt;ol class="arabic simple" start="3"&gt;
&lt;li&gt;Then did a git review after adding the script and commiting it in that dierctory :&lt;/li&gt;
&lt;/ol&gt;
&lt;pre class="literal-block"&gt;
[gkadam&amp;#64;dhcp201-114 cert-openstack-scripts]$ git review -R
Your change was committed before the commit hook was installed.
Amending the commit to add a gerrit change id.
remote: Processing changes: new: 1, refs: 1, done.
remote: (W) 9dedc09: commit subject &amp;gt;65 characters; use shorter first paragraph
remote: (W) 9dedc09: too many commit message lines longer than 70 characters; manually wrap lines
remote:
remote: New Changes:
remote:https://code.engineering.redhat.com/gerrit/73014 Add user validation, and create functions : create_member,create_network and remote:
To ssh://gkadam&amp;#64;code.engineering.redhat.com:22/cert-openstack-scripts
* [new branch]      HEAD -&amp;gt; refs/publish/master
&lt;/pre&gt;
&lt;p&gt;This was the workaround for my problem that I was facing.&lt;/p&gt;
&lt;p&gt;Here is the link to the similar issue on git : &lt;a class="reference external" href="https://help.github.com/articles/error-remote-head-refers-to-nonexistent-ref-unable-to-checkout/"&gt;Git remote HEAD Issue&lt;/a&gt;&lt;/p&gt;
</summary><category term="Gerrit"></category><category term="Git"></category></entry></feed>